main/urls.py
from django.urls import path
from . import views





app_name = 'main'
urlpatterns = [
    path('',views.Top,name="Top"),
    path('foodindex/',views.foodindex,name="foodindex"),
    path('foodwisdom',views.foodwisdom,name="foodwisdom"),
    path('recipe/',views.recipe,name="recipe"),
    path('food_rank',views.food_rank,name="food_rank"),
    path('index_top',views.index_top,name="index_top"),
    path('create_index',views.create_index,name="create_index"),
    path('create_index2',views.create_index2,name="create_index2"),
    path('edit_index/<int:num>',views.edit_index,name="edit_index"),
    path('delete_index/<int:num>',views.delete_index,name="delete_index"),
    path('find_index/',views.find_index,name="find_index"),
    path('detail_recipe/<int:num>',views.detail_recipe,name="detail_recipe"),
    path('ocr/',views.ocr,name="ocr"),
    path('detailbook',views.detailbook,name="detailbook"),
]

myprj/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
urlpatterns = [
  #path('main/', include('main.urls')),
  path('admin/', admin.site.urls),
  path(r'', include('main.urls')),
  path('authtest/',include('authtest.urls')),
  path('accounts/', include('django.contrib.auth.urls')),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    """ユーザーのモデル"""
    name = models.CharField(max_length=256)
    count = models.IntegerField(default=1)
    date = models.DateField()
    memo = models.TextField(default="")
    user = models.CharField(max_length=256)
    
    def __str__(self):
        return '<User:id=' + str(self.id) +','+ self.name + '('+ str(self.count) +')>'

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    photo = models.ImageField(upload_to='image', default='defo')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '<Documents:id=' + str(self.id) +',>'

class Recipe(models.Model):
    title = models.CharField(max_length=256)
    url = models.CharField(max_length=256)
    image_url = models.CharField(max_length=256)
    image = models.CharField(max_length=256)
    time = models.CharField(max_length=256)
    cost = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    def __str__(self):
        return '<Reccip:id=' + str(self.id) +',>'

main/python/code/forms.py
from django import forms

from ...models import *
class IndexForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name','count','date','memo','user',]
        widgets = {
            'date': forms.SelectDateWidget
        }

class FindIndex(forms.Form):
    find = forms.CharField(label='Find',required=False,widget=forms.TextInput(attrs={'class':'form-control'}))



 
 
class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        id = forms.IntegerField(label='ID')
        fields = ('description', 'photo',)

main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from .python.code import *
from .python.driver import *
from .models import *
from .python.code.forms import *
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin  

# Create your views here.
def index(req):
    return render(req, 'main/index.html')
def Top(req):
    return render(req,'main/Top.html')
def foodindex(req):
    return render(req,'main/foodindex.html')
def foodwisdom(req):
    if 'text1'in req.GET:
        a=req.GET['text1']
        if not a:
            msg="空白やめてくださいよ"
            paramas={
                'Title':msg,
            }
            return render(req,'main/foodwisdom.html',paramas) 

        r = requests.get("https://www.yasainavi.com/zukan/")
        soup = BeautifulSoup(r.content, "html.parser")

        #textで正規表現でほしいデータを抽出
    
        link=soup.find_all("a", text=re.compile(a))
        res=[]
        url=[]
        if link==[]:
            msg="ありません。カタカナ|漢字でtryしてみてください。"
            paramas={
                'Title':msg,
            }
            return render(req,'main/foodwisdom.html',paramas) 


        for i in range(0,len(link)):
            res.append(link[i].get('href'))
        for i in range(0,len(res)):
            q=requests.get("https://www.yasainavi.com/"+res[i])
            print(q.url)
            url=q.url
        paramas  ={
            'url': url,

        }
        return render(req,'main/foodwisdom.html',paramas) 
    if 'text2' in req.GET:
        a = req.GET['text2']
        if not a:
            msg="空白やめてくださいよ"
            paramas={
                'Title':msg,
            }
            return render(req,'main/foodwisdom.html',paramas) 

        r = requests.get("https://www.yasainavi.com/column/")
        soup = BeautifulSoup(r.content, "html.parser")

        #textで正規表現でほしいデータを抽出
        
        link=soup.find_all("a", text=re.compile(a))
        res=[]
        url=[]
        if link==[]:
            msg="ありません。カタカナ|漢字でtryしてみてください。"
            paramas={
                'Title':msg,
            }
            return render(req,'main/foodwisdom.html',paramas) 


        
        for i in range(0,len(link)):
            res.append(link[i].get('href'))
        for i in range(0,len(res)):
            q=requests.get("https://www.yasainavi.com/"+res[i])
            print(q.url)
            url=q.url
        paramas ={
            'url': url,

        }

        return render(req,'main/foodwisdom.html',paramas) 

    return render(req,'main/foodwisdom.html') 

def recipe(req):
    if (req.method == 'POST'):
        test = req.POST['text']

    
        url = 'https://app.rakuten.co.jp/services/api/Recipe/CategoryList/20170426?format=json&applicationId=1010512519693442205&categoryType=small&formatVersion=2'
        api_data = requests.get(url).json()
        api_data.values()
        for menu in api_data["result"]:
            print(menu)
        small_list=api_data["result"]["small"]
        res=[]

        # if 検索したい食材ワード
        for i in small_list:
            if test in  i["categoryName"]:
                res.append(list((i.items())))

        URL=""
        for i in range(len(res)):
            for j in range(0,4):
                print (res[i][j])
                if(res[i][3]):
                    URL=res[i][j][1]

        import re

        URLS=""
        URLS=re.search(r'[0-9]+-+[0-9]+-+[0-9]+', URL)
        re=URLS.group()
        re

        url = 'https://app.rakuten.co.jp/services/api/Recipe/CategoryRanking/20170426?applicationId=1010512519693442205&categoryId='+re
        api_data = requests.get(url).json()

        for menu in api_data['result']:
            menu_title = menu['recipeTitle']
            menu_url = menu['recipeUrl'] 
            menu_imageurl = menu['foodImageUrl']
            menu_image = menu['recipeMaterial']
            menu_time = menu['recipeIndication']
            menu_cost = menu['recipeCost']
            menu_description = menu['recipeDescription']

            t=Recipe(title=menu_title,url=menu_url,image_url=menu_imageurl,image=menu_image,time=menu_time,cost=menu_cost,description=menu_description)
            t.save()
 

        return redirect(to="/food_rank")     
    return render(req,'main/recipe.html') 

def ocr(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            obj = Document.objects.all()
            print(Document.objects.values('photo'))

            return redirect (to='/detailbook')
    else:
        form = DocumentForm()
        

    return render(request, 'main/ocr.html', {
        'form': form,
      
    })
    



def index_top(req):
    data=User.objects.all()
    paramas = {
        'data':data,
    }
    
    return render(req,'main/index_top.html',paramas) 


def create_index(req):
    
    if(req.method == 'POST'):
        obj = User()
        user = IndexForm(req.POST,instance=obj)
        user.save()
        return redirect(to='/find_index')
    name=req.user
    initial={
        'user':name,
    }
    form=IndexForm(req.POST or None, initial=initial)
    paramas = {
        'form':form,
    }
    return render(req,'main/create_index.html',paramas) 


def edit_index(req,num):
    obj = User.objects.get(id=num)
    if(req.method == 'POST'):
        user = IndexForm(req.POST,instance=obj)
        user.save()
        return redirect(to='/find_index')
    paramas = {
        'id':num,
        'form':IndexForm(instance=obj),
    }
    return render(req,'main/edit_index.html',paramas) 


def delete_index(req,num):
    user = User.objects.get(id=num)
    if(req.method == 'POST'):
        user.delete()
        return redirect(to='/find_index')
    paramas = {
        'id':num,
        'obj':user,
    }
    return render(req,'main/delete_index.html',paramas) 

def find_index(req):
    user=req.user
    


    if(req.method == 'POST'):
        form = FindIndex(req.POST)
        find = req.POST['find']
        data = User.objects.filter(name__contains=find,user__contains=user)
        msg = 'Result:'+str(data.count())
    else:
        msg ='search words...'
        form = FindIndex()
        data = User.objects.filter(user__contains=user)


        
        
    paramas = {
        'message':msg,
        'form':form,
        'all':data,
        
    }

    return render(req,'main/find_index.html',paramas) 

def food_rank(req):
    obj=Recipe.objects.all().order_by("id").reverse()[:4]
       
    paramas = {
        "all":obj,
        }   
    return render(req,"main/food_rank.html",paramas)





# coding:utf-8
#レシピ提案完成
import csv
import pprint
import requests
from collections import defaultdict
import os
import re


def detail_recipe(req,num):
    obj = Recipe.objects.get(id=num)
    paramas={
        "obj":obj,
    }
      

    return render(req,'main/detail_recipe.html',paramas) 

        

# coding:utf-8
import requests
from bs4 import BeautifulSoup
import re
import csv

    



module_dir = os.path.dirname(__file__)
json_path = os.path.join(module_dir, './python/driver/poised-tenure-286203-8ad31de3b8ee.json')

image_path =os.path.join(module_dir, '../media')
food_pass = os.path.join(module_dir, './python/driver/food_list.txt')
def detailbook(req):
    obj = Document.objects.latest('id')
    res=str(obj.photo)
    pas=image_path + "/" + res
    
    #各種インポート
    import io 
    import os
    from google.protobuf.json_format import MessageToJson
    import json
    from google.cloud import vision_v1
    #from google.cloud.vision import types


    #サービスアカウントキーへのパスを通す
 
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = json_path
    #visionクライアントの初期化
    client = vision_v1.ImageAnnotatorClient()

    #対象となる画像のファイル名
    file_name = pas

    
    #画像を読み込み
    try:
        with io.open(file_name, 'rb') as image_file:
            content = image_file.read()
        image = vision_v1.types.Image(content=content)
    except FileNotFoundError:
        msg="空白は、だめですよ！"
        form = DocumentForm()
        paramas={
            'Title':msg,
            'form': form,
        }
        return render(req,'main/ocr.html',paramas) 

    response = client.text_detection(image=image)
    #最初のtextのまとめが[0]に格納されている。
    texts = response.text_annotations[0]
    #print('Texts:')


    #print('\n"{}"'.format(texts.description))

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))
    
    #検索
    f = open(food_pass, encoding='CP932')
    data1 = f.read()
    lines = data1.split('\n')
    f.close()

    text=texts.description
    tex=text.split('\n')

    # レシートから読み込んだ文字列を表示
    search_words = []
    for word in lines:
        for receipt in tex:
            if word in receipt:
                #空行削除
                if word !='':
                    search_words.append(word)
                #print("True")


    paramas={
        'obj':res,
        'item':search_words,

    }
    if req.method == 'POST':
        msg=req.POST.getlist('text')
        print(msg)

        par={
            'msg':msg,

        }
        return render(req, 'main/create_index2.html', par)



    return render(req, 'main/detailbook.html', paramas)
    

def create_index2(req):

    name=req.user
    
    msg = req.POST['text']
    item=IndexForm(initial={'name':msg})
    paramas = {
        'form':item,
    }
    req.POST.update()

    if(req.method == 'POST'):
        if(req.POST['text']):
            msg = req.POST['text']
            item=IndexForm(initial={'name':msg,'user':name})
            paramas = {
                    'form':item,
                    'name':name,
            }
            return render(req,'main/create_index2.html',paramas)
    obj = User()
    user = IndexForm(req.POST,instance=obj)

main/templates/main/Top.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Recci</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
<body>
  <header>
    <center>
    <h1 id="title">Recci</h1>
    <div class="right">
    <ul>  
        {% if user.is_authenticated %}
        <li><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材登録</a></li>
        {% endif %}
       <li><a href="{% url 'main:recipe'  %}">レシピ検索</a></li>
       <li><a href="{% url 'main:foodwisdom' %}">食育</a></li>
    </ul>
    </div>
    </center>
  </header>

<div class="contents">
  <br>
  {% if user.is_authenticated %}
  <p>Recciへようこそ {{ user.username }}さん!</p>
  <a href="{% url 'logout' %}" class="logout">ログアウト</a>
  {% else %}
  <p>You are not logged in.</p>
  <p><a href="{% url 'login' %}">ログイン</a></p>
  <p><a href="{% url 'signup' %}">サインアップ</a></p>
  {% endif %}

 
  <hr>
<center>

  {% if user.is_authenticated %}
  <h2><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材を登録する</a></h2>
  {% endif %}

  <h2> <a href="{% url 'main:recipe'  %}">レシピを検索する</a></h2>

  <h2><a href="{% url 'main:foodwisdom' %}">食材の加工法・保存法を見る</a></h2>
</center>
</div>
</body>
</html>

main/templates/main/create_index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Recci/食品登録</title>
  <meta charset="ytf-8">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
 <body>
    <header>
        <center>
        <h1 id="title">Recci</h1>
        <div class="right">
        <ul>  
            {% if user.is_authenticated %}
            <li><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材登録</a></li>
            {% endif %}
           <li><a href="{% url 'main:recipe'  %}">レシピ検索</a></li>
           <li><a href="{% url 'main:foodwisdom' %}">食育</a></li>
        </ul>
        </div>
        </center>
    </header>

    <div class="contents">
     <h1>食品登録</h1>
     <form action="{% url 'main:create_index' %}" method="post">
         {% csrf_token %}
         <table class="table">
             {{ form }}
             <tr><th><td>
                <input type = "submit" value="登録" class="button">
            </td></th></tr>
         </table>
       
     </form>
     <br>
     <br>
     <td><a href="{% url 'main:foodindex' %}">戻る</a></td>
     </div>
 </body>
</html>

main/templates/main/create_index2.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Recci/食品登録OCR</title>
  <meta charset="ytf-8">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
 <body class="container">
     <h1>食品登録 OCR</h1>
     {% csrf_token %}
     <form action="{% url 'main:create_index' %}" method="POST">
         {% csrf_token %}
         <table class="table">
             {{ form }}
             
             <tr><th><td>
                <input type = "submit" value="click" class="button">
            </td></th></tr>
         </table>
       
     </form>
     <br>
     <br>
     <td><a href="{%url 'main:detailbook' %}">戻る</a></td>

 </body>
</html>

main/templates/main/delete_index.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta charset="ytf-8">
  <title>Recci/履歴削除</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
 <body class="container">

    <p>以下のレコードを削除します  </p>
         <table class="table">
             <tr><th>ID</th><td>{{ obj.id }}</td></tr>
             <tr><th>Name</th><td>{{ obj.name }}</td></tr>
             <tr><th>Count</th><td>{{ obj.count }}</td></tr>
             <tr><th>Date</th><td>{{ obj.date }}</td></tr>
             <tr><th>Memo</th><td>{{ obj.memo }}</td></tr>
             <form action="{% url 'main:delete_index' id %}" method="post">
                 {% csrf_token %}
                 <tr><th><td>
                     <input type = "submit" value="click" class="button">
                </td></th></tr>
             </form>
         </table>

 </body>
</html>

main/templates/main/detailbook.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta charset="ytf-8">
  <title>Recci/食育</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
    <body>
        <table>
            <tr>
                <td><img src="../../../media/{{ obj }}" width="450" height="450"/></td>
            </tr>
            <tr>
            <form action="{%url 'main:create_index2' %}" method="POST">
                    <label for ="text">foodname:</label>
                {% for search_words in item %}
                    {% csrf_token %}
                    <input id = "{{search_words}}" type="radio" name="text" value={{search_words}}>{{search_words}}
        
                {% endfor %}
                    <input type="submit"  value="送信">
            </form>
            </tr>
            <p>※使いたい食材を入力してください</p>


            <h2><a href="{%url 'main:ocr' %}">写真に戻る</a></h2> 
        </table>
    </body>
</html>

main/templates/main/edit_index.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta charset="ytf-8">
  <title>Recci/履歴編集</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
 <body class="container">

     <form action="{% url 'main:edit_index' id %}" method="post">
         {% csrf_token %}
         <table class="table">
             {{ form }}
             <tr><th><td>
                <input type = "submit" value="click">
            </td></th></tr>
         </table>
       
     </form>
 </body>
</html>

main/templates/main/find_index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta charset="ytf-8">
  <title>Recci/食材登録履歴</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
 <body>
    <header>
        <center>
        <h1 id="title">Recci</h1>
        <div class="right">
        <ul>  
            {% if user.is_authenticated %}
            <li><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材登録</a></li>
            {% endif %}
           <li><a href="{% url 'main:recipe'  %}">レシピ検索</a></li>
           <li><a href="{% url 'main:foodwisdom' %}">食育</a></li>
        </ul>
        </div>
        </center>
    </header>

<div class="contents">
     <h1>登録食品履歴</h1>
     <p>キーワード検索</p>
     <form action="{% url 'main:find_index' %}" method="post">
         {% csrf_token %}
         {{ form }}
         <tr><th><td>
            <input type = "submit" value="検索" class="button">
        </td></th></tr>
     </form>
     <hr>

     <table class="table">
        <table border="1">
            <tr>
            <th>食品名</th>
            <th>個数</th>
            <th>賞味期限</th>
            <th></th>
            <th></th>

            </tr>
        {% for item in all %}
            <tr>

                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.count }}</td>
                    <td>{{ item.date }}</td>
                    <td><a href="{% url 'main:edit_index' item.id %}">編集</a></td>
                    <td><a href="{% url 'main:delete_index' item.id %}">削除</a></td>
                       
                </tr>
 
            </tr>   
        {% endfor %}
    </table>
    </table>
     
     <br>
     <br>
     <td><a href="{% url 'main:foodindex' %}">戻る</a></td>
     <td><a href="{% url 'main:recipe' %}">レシピへ</a></td>
</div>
 </body>
</html>

main/templates/main/food_rank.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta charset="ytf-8">
  <title>Recci/レシピランキング</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
    <body>

        <tr>
            <td>  
                {% for item in all %}
                <center>
                <a href="{%url 'main:detail_recipe'  item.id %}" class="recipecontent">
                    <div>
                    <h2> {{ item.title }}</h2> <br>
                    <img src="{{item.image_url}}" alt="{{ item.title}} " class="rankimg">
                </div>
            </a>
            <br><br><hr><br>
            </center>
                {% endfor %}
               <br>
               <br>{% csrf_token %}
             

            </td>
        </tr>
        <h2><a href="{%url 'main:recipe'%}">レシピ検索に戻る</a></h2> 

    </body>
</html>

main/templates/main/foodindex.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta charset="ytf-8">
  <title>Recci/食材登録</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>

  <body>
    <header>
      <center>
      <h1 id="title">Recci</h1>
      <div class="right">
      <ul>  
          {% if user.is_authenticated %}
          <li><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材登録</a></li>
          {% endif %}
         <li><a href="{% url 'main:recipe'  %}">レシピ検索</a></li>
         <li><a href="{% url 'main:foodwisdom' %}">食育</a></li>
      </ul>
      </div>
      </center>
  </header>
  <div class="contents">
    <h1>食材登録</h1>
      <h2><a href="{%url 'main:ocr'%}">レシートから登録する</a></h2>

      <h2><a href="{%url 'main:create_index'%}">直接入力する</a></h2>

      <h2><a href="{%url 'main:find_index'%}">登録履歴をみる</a></h2>


      <h2><a href="{%url 'main:Top'%}">ホームに戻る</a></h2>

  </div>
  </body>

  </html>

main/templates/main/foodwisdom.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Recci/食育</title>
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <script type="text/javascript" src="{% static 'script.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>
<body>
  <header>
    <center>
    <h1 id="title">Recci</h1>
    <div class="right">
    <ul>  
        {% if user.is_authenticated %}
        <li><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材登録</a></li>
        {% endif %}
       <li><a href="{% url 'main:recipe'  %}">レシピ検索</a></li>
       <li><a href="{% url 'main:foodwisdom' %}">食育</a></li>
    </ul>
    </div>
    </center>
  </header>

<div class="contents">
       <h1>食育 </h1>
       <h2>{{Title}}</h2>
    <p>使いたい食材を入力してください</p>
    <form action="{% url 'main:foodwisdom' %}">
        {% csrf_token %}
        <label for ="text">食材の知識:</label>
        <input id = "text" type="text" name="text1" >
        <input type="submit"  value="検索" class="button">
    </form>
        <br>
    <form action="{% url 'main:foodwisdom' %}">
        {% csrf_token %}
        <label for ="text">包丁の扱い方や食材の保存方法:</label> 
        <input id = "text" type="text" name="text2" >
        <input type="submit"  value="検索" class="button">
    </form>
    <p>URL：<a href=" {{ url }}">{{ url }} </a></p>

<h2><a href="{%url 'main:Top'%}">ホームに戻る</a></h2>
</div>
</body>
</html>

main/templates/main/ocr.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta charset="ytf-8">
  <title>Recci/レシート読み取り</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script type="text/javascript" src="{% static 'style.js' %}"></script>
</head>
    <body>
        <header>
            <center>
            <h1 id="title">Recci</h1>
            <div class="right">
            <ul>  
                {% if user.is_authenticated %}
                <li><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材登録</a></li>
                {% endif %}
               <li><a href="{% url 'main:recipe'  %}">レシピ検索</a></li>
               <li><a href="{% url 'main:foodwisdom' %}">食育</a></li>
            </ul>
            </div>
            </center>
        </header>
        <div class="contents">
            <h1>レシート読み取り</h1>
            <h2>{{Title}}</h2>
        <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">読み込む</button>
        </form>

    <br>
    <td><a href="{% url 'main:foodindex' %}">戻る</a></td>
</div>    
</body>
</html>

main/templates/main/recipe.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Recci/レシピ検索</title>
        <link rel="stylesheet" href="{% static 'style.css' %}"/>
        <script type="text/javascript" src="{% static 'script.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>
<body>
    <header>
        <center>
        <h1 id="title">Recci</h1>
        <div class="right">
        <ul>  
            {% if user.is_authenticated %}
            <li><a href="{% url 'main:foodindex' %}" class="btn btn--yellow btn--cubic">食材登録</a></li>
            {% endif %}
           <li><a href="{% url 'main:recipe'  %}">レシピ検索</a></li>
           <li><a href="{% url 'main:foodwisdom' %}">食育</a></li>
        </ul>
        </div>
        </center>
      </header>

<div class="contents">

    <h1>レシピ検索</h1>
   
    <p>使いたい食材を入力してください</p>
    <form action="{% url 'main:recipe' %}" method="POST">
        {% csrf_token %}
        <label for ="text">食材名:</label>
        <input id = "text" type="text" name="text">
        <input type="submit"  value="検索" class="button">
    </form>
    <h2><a href="{%url 'main:Top'%}">ホームに戻る</a></h2> 
    </div>
</body>
</html>